openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Collage API
    description: Generates Collages
  - name: Collage API
    description: Downloads Collages
paths:
  /api/generate:
    post:
      tags:
        - Collage API
      summary: Generate a collage
      description: This action generates a collage based the experiences guests have
        booked. You must use the QueryRecords action to fetch the contact record by
        name and ask the user for a quote before executing the action.
      operationId: generate
      parameters:
        - name: contactId
          in: query
          description: A record Id for the contact related to the experience booking
            records
          required: true
          schema:
            type: string
            description: A record Id for the contact related to the experience booking
              records
            example: Guest contact ID
          example: Guest contact ID
        - name: quote
          in: query
          description: A personalized message to display on the collage relating to
            what the user most enjoyed about their stay at the resort.
          required: true
          schema:
            type: string
            description: A personalized message to display on the collage relating to
              what the user most enjoyed about their stay at the resort.
            example: Oh my goodness those sunsets!
          example: Oh my goodness those sunsets!
      responses:
        "200":
          description: Download URL for the generated collage
          content:
            text/plain:
              schema:
                type: string
                example: https://coralcloud-collage-action.herokuapp.com/download/d938eba6-100b-426a-adf2-c9bec87412b0.png
        "400":
          description: Invalid input data
          content:
            text/plain:
              schema:
                type: string
                example: error:No valid images were loaded.
  /download/{id}:
    get:
      tags:
        - Collage API
      summary: Download a collage
      description: Downloads a collage created with the /api/generate operation.
      operationId: downloadFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
components: {}
